#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include "persist_service.h"

using ::testing::_;
using ::testing::HasSubstr;
using ::testing::Return;
using ::testing::StrictMock;

namespace {

// Mocks are just subclasses whose virtual methods are generated by MOCK_METHOD.
// Syntax: MOCK_METHOD(ReturnType, name, (params...), (qualifiers...));
class MockEventStore : public j2c::EventStore {
 public:
  MOCK_METHOD(uint64_t, lastIndex, (), (const, override));
  MOCK_METHOD(bool, persist, (uint64_t index, const std::string &payload), (override));
};

class MockNotifier : public j2c::Notifier {
 public:
  MOCK_METHOD(void, onPersisted, (uint64_t commandId, uint64_t index), (override));
  MOCK_METHOD(void, onPersistFailed, (uint64_t commandId, const std::string &reason), (override));
};

// Fixture == JUnit class with @BeforeEach-initialized fields.
// StrictMock fails the test on any call we didn't EXPECT_CALL.
class PersistServiceTest : public ::testing::Test {
 protected:
  StrictMock<MockEventStore> mStore;
  StrictMock<MockNotifier> mNotifier;
};

}  // namespace

TEST_F(PersistServiceTest, PersistsAtNextIndexAndNotifies) {
  j2c::PersistService service(mStore, mNotifier, 3);

  EXPECT_CALL(mStore, lastIndex()).WillOnce(Return(41));
  EXPECT_CALL(mStore, persist(42, "payload")).WillOnce(Return(true));
  EXPECT_CALL(mNotifier, onPersisted(7, 42));

  service.submit(7, "payload");
}

TEST_F(PersistServiceTest, RetriesUntilSuccess) {
  j2c::PersistService service(mStore, mNotifier, 3);

  EXPECT_CALL(mStore, lastIndex()).WillOnce(Return(0));
  EXPECT_CALL(mStore, persist(1, _))
      .WillOnce(Return(false))
      .WillOnce(Return(false))
      .WillOnce(Return(true));
  EXPECT_CALL(mNotifier, onPersisted(9, 1));

  service.submit(9, "x");
}

TEST_F(PersistServiceTest, GivesUpAfterMaxAttempts) {
  j2c::PersistService service(mStore, mNotifier, 3);

  EXPECT_CALL(mStore, lastIndex()).WillOnce(Return(0));
  EXPECT_CALL(mStore, persist(_, _)).Times(3).WillRepeatedly(Return(false));
  EXPECT_CALL(mNotifier, onPersistFailed(5, HasSubstr("after 3 attempts")));

  service.submit(5, "x");
}

TEST_F(PersistServiceTest, EmptyPayloadNeverHitsStore) {
  j2c::PersistService service(mStore, mNotifier, 3);

  // No EXPECT_CALL on mStore: StrictMock makes any call a failure.
  EXPECT_CALL(mNotifier, onPersistFailed(1, "empty payload"));

  service.submit(1, "");
}

// TODO(you): add the two tests described in README.md here.
